import { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./com/navbar";
import Footer from "./com/footer";
const inter = Inter({ subsets: ["latin"] });

import { FormProvider } from './context/FormContext';




export const metadata = {
  title: "Onlyfans",
  description: "Generated by Subham",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
     
    >
    <html lang="en">
            <body className={`${inter.className} bg-gray-950 text-white`}>
              
              
              <Navbar/>
            
        <FormProvider>{children}</FormProvider>
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
